/**
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionCommitError } from './TransactionCommitError';
import { HttpFile } from '../http/http';

export class TransactionCommitErrorResponse {
    'data': Array<TransactionCommitError>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<TransactionCommitError>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionCommitErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

