/**
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Cursor } from './Cursor';
import { CursorResponse } from './CursorResponse';
import { Transaction } from './Transaction';
import { TransactionCursorAllOf } from './TransactionCursorAllOf';
import { HttpFile } from '../http/http';

export class TransactionListResponse {
    'cursor'?: Cursor;
    'data': Array<Transaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "Cursor",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Transaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

